Repository animal-squad/project-s-ai, pull requests merged in 2024-11, with the labels that each got.

#12 #11 Feat: 태그 부여 기능 수정
  entity/link_info.py
  entity/request_dto.py
  entity/response_dto.py
  main.py
  service/categorize_service.py
Labels: 기능 추가

#14 #13 Feat: 컨텐츠 없을 때의 대안 기능 추가
  service/content_reader.py
  service/crawlability_checker.py
Labels: 기능 추가

#18 #15 Feat: 본문 정보 유무에 따른 태그 부여 기능 - 본문 무
  README.md
  entity/link_info.py
  main.py
  requirement.txt
  service/categorize_service.py
  service/content_reader.py
  service/crawlability_checker.py
Labels: 기능 추가

#17 #16 Feat: 본문 정보 유무에 따른 태그 부여 기능 - 본문 유
  service/content_extractor.py
Labels: 기능 추가

#22 Feat: 태그 부여 서버 v0.0.1
  README.md
  entity/__init__.py
  entity/link_info.py
  entity/request_dto.py
  entity/response_dto.py
  main.py
  model/__init__.py
  model/gpt_model.py
  prompt/main_category
  requirement.txt
  service/__init__.py
  service/categorize_service.py
  service/content_extractor.py
  service/content_reader.py
  service/crawlability_checker.py
Labels: 기능 추가

#25 #23 CI/CD: Dockerfile && Jenkinsfile 추가
  Dockerfile
  Jenkinsfile
Labels: CI/CD

#27 #23 Fix: 중괄호 누락 수정
  Jenkinsfile
Labels: 버그 수정

#30 #29 FIX: Jenkinsfile 수정
  Jenkinsfile
Labels: 버그 수정, CI/CD
